# Generated by Django 5.0.6 on 2024-06-16 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('jan', models.CharField(blank=True, max_length=20, null=True)),
                ('feb', models.CharField(blank=True, max_length=20, null=True)),
                ('mar', models.CharField(blank=True, max_length=20, null=True)),
                ('apr', models.CharField(blank=True, max_length=20, null=True)),
                ('may', models.CharField(blank=True, max_length=20, null=True)),
                ('jun', models.CharField(blank=True, max_length=20, null=True)),
                ('jul', models.CharField(blank=True, max_length=20, null=True)),
                ('aug', models.CharField(blank=True, max_length=20, null=True)),
                ('sep', models.CharField(blank=True, max_length=20, null=True)),
                ('oct', models.CharField(blank=True, max_length=20, null=True)),
                ('nov', models.CharField(blank=True, max_length=20, null=True)),
                ('dec', models.CharField(blank=True, max_length=20, null=True)),
                ('win', models.CharField(blank=True, max_length=20, null=True)),
                ('spr', models.CharField(blank=True, max_length=20, null=True)),
                ('sum', models.CharField(blank=True, max_length=20, null=True)),
                ('aut', models.CharField(blank=True, max_length=20, null=True)),
                ('ann', models.CharField(blank=True, max_length=20, null=True)),
                ('weather_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='weather.weatherurl')),
            ],
        ),
    ]
